// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mrfnypacardgylimjxkw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yZm55cGFjYXJkZ3lsaW1qeGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NjA3NDQsImV4cCI6MjA0OTEzNjc0NH0.PP-wJ-ioqwkKrgFUoCXtzxFNmAILSDWClFhWeX9UOj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);